            - name: Duplicate code detection tool
  # You may pin to the exact commit or the version.
  # uses: platisd/duplicate-code-detection-tool@f0413b1571a98b653f617a59fec0097001e18c0e
  uses: platisd/duplicate-code-detection-tool@v1.2.0
  with:
    # The GitHub token
    github_token: 
    # A comma-separated list of the directories containing the source code
    directories: 
    # A comma-separated list of directories that should be ignored
    ignore_directories: # optional, default is 
    # The relative path to filter out when reporting results
    project_root_dir: # optional, default is ./
    # A comma-separated list of source code file extensions to check for similarities
    file_extensions: # optional, default is h, hpp, c, cpp, cc, java, py, cs
    # The minimum similarity percentage to be reported
    ignore_below: # optional, default is 10
    # The maximum allowed similarity percentage before the action fails
    fail_above: # optional, default is 100
    # The maximum allowed similarity percentage before the action warns
    warn_above: # optional, default is 100
    # Removes comments and docstrings from the source code before analysis
    only_code: # optional
    # Duplication report will be left as a single comment, which will be updated, instead of multiple ones
    one_comment: # optional
    # The message to be displayed at the start of the duplication report. It is used by the bot to identify previous reports and update them, so it must be unique. If you want to use the Action in multiple steps of the same workflow, then you can change this message in each step to avoid conflicts
    header_message_start: # optional, default is ## 📌 Duplicate code detection tool report
          
